M48
; DRILL file {KiCad 9.0.0} date 2025-03-22T03:19:09+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-22T03:19:09+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X144.78Y-129.254
X168.98Y-129.254
T2
X154.455Y-40.321
X159.305Y-40.321
T3
X154.155Y-37.291
X159.605Y-37.291
M30
