M48
; DRILL file {KiCad 9.0.0} date 2025-03-20T22:52:41+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-20T22:52:41+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X92.9Y-120.5
X117.1Y-120.5
T2
X102.575Y-31.567
X107.425Y-31.567
T3
X102.275Y-28.537
X107.725Y-28.537
M30
